deploy:
  - on:
      repo: joneshf/purescript-webstorage
      tags: true
    provider: script
    script: ./script/travis_pulp_publish.sh --token $GITHUB_PULP_TOKEN
    skip_cleanup: true

install:
  - npm install
  - npm run bower -- install

language: node_js

node_js: 8

notifications:
  email: false

script:
  - npm run build
  - ./script/travis_dirty_working_tree.sh

env:
  global:
    - secure: UpaTxaFgiwXGAv0R6dpplNDT4XvfoDlgmDIncBhYTx4OHVOF0Zo4AmUbwGVGsS+T/i8kAbVt39GunmJjmFpruI2Rtay7IzCfOhvNsFZcBEc0Sko/USpbPxiROrMMWYGCQSU4GI3YxP8/mtMNdyARz4OY6Y12ak9Zzzj8DtYs/gA=
